#!/bin/bash

#Do NFS stuff
cat <<EOF> /etc/exports
${S3QL_MOUNT_POINT} ${S3QL_SUBNET}(fsid=0,rw,sync,insecure,no_subtree_check,anonuid=1000,anongid=1000,crossmnt)
EOF
exportfs -rav
service rpcbind restart
service nfs-kernel-server restart

umask 0377

#Check for authfile presence and create from environment variables.
if [[ ! -f /root/.s3ql/authinfo2 ]]
then
  mkdir -p /root/.s3ql
  cat <<EOF > /root/.s3ql/authinfo2
[s3ql]
storage-url: ${S3QL_URL}
backend-login: ${S3QL_LOGIN}
backend-password: ${S3QL_PASSWD}
fs-passphrase: ${S3QL_FSPASSWD}
EOF
  cat /root/.s3ql/authinfo2
fi

mkdir -p ${S3QL_MOUNT_POINT}
cat <<EOF
: fsck.s3ql "${S3QL_URL}/${S3QL_STORAGE}/"
EOF
  fsck.s3ql "${S3QL_URL}/${S3QL_STORAGE}/"
signal=$?

if [[ ${signal} -eq 18 ]]
then
  cat <<EOF
: FSCK did not find a Filesystem, Creating new
: mkfs.s3ql --plain --max-obj-size "${S3QL_MAX_OBJ_SIZE}" "${S3QL_URL}/${S3QL_STORAGE}/"
EOF
  mkfs.s3ql --plain --max-obj-size "${S3QL_MAX_OBJ_SIZE}" "${S3QL_URL}/${S3QL_STORAGE}/"
elif [[ ${signal} -ne 0 ]]
then
  echo "FSCK failed, Refusing to mount, please fix errors manually"
  exit 1
fi

s3ql_mount_option="--fg --nfs --allow-other --log ${S3QL_LOGFILE} --compress ${S3QL_COMPRESS}"

if [[ ! "${S3QL_CACHESIZE}x" = "x" ]]; then
  cat <<EOF
: mount.s3ql ${s3ql_mount_option} --cachesize "${S3QL_CACHESIZE}" "${S3QL_URL}/${S3QL_STORAGE}/" "${S3QL_MOUNT_POINT}"
EOF
  mount.s3ql ${s3ql_mount_option} --cachesize "${S3QL_CACHESIZE}" "${S3QL_URL}/${S3QL_STORAGE}/" "${S3QL_MOUNT_POINT}"
else
  cat <<EOF
: mount.s3ql ${s3ql_mount_option} "${S3QL_URL}/${S3QL_STORAGE}/" "${S3QL_MOUNT_POINT}"
EOF
  mount.s3ql ${s3ql_mount_option} "${S3QL_URL}/${S3QL_STORAGE}/" "${S3QL_MOUNT_POINT}"
fi
